// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SNM.Master.Data;

#nullable disable

namespace SNM.Master.Data.Migrations
{
    [DbContext(typeof(SnmDbContext))]
    partial class SnmDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("SNM.Master.Data.Entities.AdminUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Avatar")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("FailedLogins")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LockedUntil")
                        .HasColumnType("TEXT");

                    b.Property<string>("NickName")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PasswordChangedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("TokenVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("AdminUsers", (string)null);
                });

            modelBuilder.Entity("SNM.Master.Data.Entities.AlertEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("AcknowledgedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DedupKey")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int?>("NodeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NodeName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Notified")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Rule")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Severity")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<double>("Threshold")
                        .HasColumnType("REAL");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<double>("Value")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("StartedAt")
                        .HasDatabaseName("IX_AlertEvents_StartedAt");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_AlertEvents_Status");

                    b.HasIndex("NodeId", "StartedAt")
                        .HasDatabaseName("IX_AlertEvents_NodeId_StartedAt");

                    b.ToTable("AlertEvents", (string)null);
                });

            modelBuilder.Entity("SNM.Master.Data.Entities.AlertState", b =>
                {
                    b.Property<int>("NodeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Rule")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Subject")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("Consecutive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CooldownUntil")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FiringSince")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastNotifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("LastValue")
                        .HasColumnType("REAL");

                    b.Property<long?>("OpenEventId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ResolveCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("NodeId", "Rule", "Subject");

                    b.ToTable("AlertStates", (string)null);
                });

            modelBuilder.Entity("SNM.Master.Data.Entities.InstallToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastUsedIp")
                        .HasMaxLength(45)
                        .HasColumnType("TEXT");

                    b.Property<int>("NodeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(43)
                        .HasColumnType("TEXT");

                    b.Property<int>("UsedCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("NodeId");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.ToTable("InstallTokens", (string)null);
                });

            modelBuilder.Entity("SNM.Master.Data.Entities.Metric1d", b =>
                {
                    b.Property<int>("NodeId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Ts")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CpuAvg")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CpuMax")
                        .HasColumnType("INTEGER");

                    b.Property<long>("DiskTotalMb")
                        .HasColumnType("INTEGER");

                    b.Property<long>("DiskUsedMb")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Load1Avg")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Load1Max")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MemUsedAvgMb")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MemUsedMaxMb")
                        .HasColumnType("INTEGER");

                    b.Property<long>("RxBpsAvg")
                        .HasColumnType("INTEGER");

                    b.Property<long>("RxBpsMax")
                        .HasColumnType("INTEGER");

                    b.Property<long>("RxBytes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Samples")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SwapUsedAvgMb")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TxBpsAvg")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TxBpsMax")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TxBytes")
                        .HasColumnType("INTEGER");

                    b.HasKey("NodeId", "Ts");

                    b.HasIndex("Ts")
                        .HasDatabaseName("IX_Metrics1d_Ts");

                    b.ToTable("Metrics1d", (string)null);
                });

            modelBuilder.Entity("SNM.Master.Data.Entities.Metric1h", b =>
                {
                    b.Property<int>("NodeId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Ts")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CpuAvg")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CpuMax")
                        .HasColumnType("INTEGER");

                    b.Property<long>("DiskTotalMb")
                        .HasColumnType("INTEGER");

                    b.Property<long>("DiskUsedMb")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Load1Avg")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Load1Max")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MemUsedAvgMb")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MemUsedMaxMb")
                        .HasColumnType("INTEGER");

                    b.Property<long>("RxBpsAvg")
                        .HasColumnType("INTEGER");

                    b.Property<long>("RxBpsMax")
                        .HasColumnType("INTEGER");

                    b.Property<long>("RxBytes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Samples")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SwapUsedAvgMb")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TxBpsAvg")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TxBpsMax")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TxBytes")
                        .HasColumnType("INTEGER");

                    b.HasKey("NodeId", "Ts");

                    b.HasIndex("Ts")
                        .HasDatabaseName("IX_Metrics1h_Ts");

                    b.ToTable("Metrics1h", (string)null);
                });

            modelBuilder.Entity("SNM.Master.Data.Entities.Metric1m", b =>
                {
                    b.Property<int>("NodeId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Ts")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CpuAvg")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CpuMax")
                        .HasColumnType("INTEGER");

                    b.Property<long>("DiskTotalMb")
                        .HasColumnType("INTEGER");

                    b.Property<long>("DiskUsedMb")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Load1Avg")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Load1Max")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MemUsedAvgMb")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MemUsedMaxMb")
                        .HasColumnType("INTEGER");

                    b.Property<long>("RxBpsAvg")
                        .HasColumnType("INTEGER");

                    b.Property<long>("RxBpsMax")
                        .HasColumnType("INTEGER");

                    b.Property<long>("RxBytes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Samples")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SwapUsedAvgMb")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TxBpsAvg")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TxBpsMax")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TxBytes")
                        .HasColumnType("INTEGER");

                    b.HasKey("NodeId", "Ts");

                    b.HasIndex("Ts")
                        .HasDatabaseName("IX_Metrics1m_Ts");

                    b.ToTable("Metrics1m", (string)null);
                });

            modelBuilder.Entity("SNM.Master.Data.Entities.Node", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdminRemark")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentKey")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentVersion")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<bool>("AlertsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Arch")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<bool>("AutoRenew")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BillingCycleMonths")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("BootTimeUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("CountryCodeAuto")
                        .HasMaxLength(2)
                        .HasColumnType("TEXT");

                    b.Property<string>("CountryCodeOverride")
                        .HasMaxLength(2)
                        .HasColumnType("TEXT");

                    b.Property<int?>("CpuAlertPct")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CpuCores")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CpuModel")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<int?>("DiskAlertPct")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisksJson")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FirstSeenAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Hostname")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("IntervalMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Kernel")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("KeyRotatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastRegisterAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastRemoteIp")
                        .HasMaxLength(45)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastSeenAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("MemTotalMb")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NetIfs")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int?>("OfflineAlertSec")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Os")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProtocolVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PublicName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<bool>("PublicVisible")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RenewUrl")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("StatusChangedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("SwapTotalMb")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TimeZoneId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int?>("TrafficAlertPct")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TrafficCountMode")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TrafficLimitBytes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TrafficResetDay")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Vendor")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Virt")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AgentKey")
                        .IsUnique()
                        .HasDatabaseName("UX_Nodes_AgentKey");

                    b.HasIndex("PublicName")
                        .IsUnique()
                        .HasDatabaseName("UX_Nodes_PublicName");

                    b.HasIndex("SortOrder")
                        .HasDatabaseName("IX_Nodes_SortOrder");

                    b.ToTable("Nodes", (string)null);
                });

            modelBuilder.Entity("SNM.Master.Data.Entities.NodeIp", b =>
                {
                    b.Property<int>("NodeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasMaxLength(45)
                        .HasColumnType("TEXT");

                    b.Property<int>("Family")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FirstSeenAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastSeenAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Source")
                        .HasColumnType("INTEGER");

                    b.HasKey("NodeId", "Address");

                    b.HasIndex("LastSeenAt")
                        .HasDatabaseName("IX_NodeIps_LastSeenAt");

                    b.ToTable("NodeIps", (string)null);
                });

            modelBuilder.Entity("SNM.Master.Data.Entities.NotificationChannel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConfigJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastError")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastSuccessAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastTestAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("MinSeverity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("RuleMask")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("NotificationChannels", (string)null);
                });

            modelBuilder.Entity("SNM.Master.Data.Entities.NotificationDelivery", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Attempt")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChannelName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ElapsedMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Error")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<long?>("EventId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Ok")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StatusCode")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ChannelId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("EventId");

                    b.ToTable("NotificationDeliveries", (string)null);
                });

            modelBuilder.Entity("SNM.Master.Data.Entities.RefreshToken", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ip")
                        .HasMaxLength(45)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReplacedByHash")
                        .HasMaxLength(44)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(44)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens", (string)null);
                });

            modelBuilder.Entity("SNM.Master.Data.Entities.Setting", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("Settings", (string)null);
                });

            modelBuilder.Entity("SNM.Master.Data.Entities.TrafficDaily", b =>
                {
                    b.Property<int>("NodeId")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<long>("RxBytes")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TxBytes")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("NodeId", "Date");

                    b.ToTable("TrafficDaily", (string)null);
                });

            modelBuilder.Entity("SNM.Master.Data.Entities.TrafficMonthly", b =>
                {
                    b.Property<int>("NodeId")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("PeriodStart")
                        .HasColumnType("TEXT");

                    b.Property<long>("BilledBytes")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Closed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CountMode")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LimitBytes")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("PeriodEnd")
                        .HasColumnType("TEXT");

                    b.Property<int>("ResetDay")
                        .HasColumnType("INTEGER");

                    b.Property<long>("RxBytes")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TxBytes")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("NodeId", "PeriodStart");

                    b.ToTable("TrafficMonthly", (string)null);
                });

            modelBuilder.Entity("SNM.Master.Data.Entities.TrafficState", b =>
                {
                    b.Property<int>("NodeId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("BootTimeAtPrevUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PrevAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("PrevConnectionId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long>("PrevRx")
                        .HasColumnType("INTEGER");

                    b.Property<long>("PrevTx")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("NodeId");

                    b.ToTable("TrafficState", (string)null);
                });

            modelBuilder.Entity("SNM.Master.Data.Entities.AlertEvent", b =>
                {
                    b.HasOne("SNM.Master.Data.Entities.Node", null)
                        .WithMany()
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("SNM.Master.Data.Entities.AlertState", b =>
                {
                    b.HasOne("SNM.Master.Data.Entities.Node", null)
                        .WithMany()
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SNM.Master.Data.Entities.InstallToken", b =>
                {
                    b.HasOne("SNM.Master.Data.Entities.Node", null)
                        .WithMany()
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SNM.Master.Data.Entities.NodeIp", b =>
                {
                    b.HasOne("SNM.Master.Data.Entities.Node", null)
                        .WithMany()
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SNM.Master.Data.Entities.NotificationDelivery", b =>
                {
                    b.HasOne("SNM.Master.Data.Entities.NotificationChannel", null)
                        .WithMany()
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SNM.Master.Data.Entities.AlertEvent", null)
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SNM.Master.Data.Entities.RefreshToken", b =>
                {
                    b.HasOne("SNM.Master.Data.Entities.AdminUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SNM.Master.Data.Entities.TrafficState", b =>
                {
                    b.HasOne("SNM.Master.Data.Entities.Node", null)
                        .WithOne()
                        .HasForeignKey("SNM.Master.Data.Entities.TrafficState", "NodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
